[book]
authors = ["cr0mll"]
language = "en"
multilingual = false
src = "Notes"
title = "The Cyberclopaedia"
description = "This is an aspiring project aimed at accumulating knowledge from the world of cybersecurity and presenting it in a cogent way, so it is accessible to as large and audience as possible and so that everyone has a good resource to learn hacking from."

[preprocessor.katex]
renderers = ["html"]
after = ["links"]

[output.html]
no-section-label = true
default-theme = "coal"
git-repository-url = "https://github.com/cr0mll/cyberclopaedia/"
git-repository-icon = "fa-github"
mathjax-support = true

[output.html.fold]
enable = true

[build]
build-dir = "docs"
create-missing = false